# Railway configuration for the Orchestrator Worker
[build]
buildCommand = "npm install -g pnpm && pnpm install --frozen-lockfile"

[deploy]
startCommand = "node workers/orchestrator.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10