# Railway configuration for the Orchestrator Worker
[build]
builder = "RAILPACKS"
buildCommand = "pnpm install"

[deploy]
startCommand = "node workers/orchestrator.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "20"
PNPM_VERSION = "9"