# Railway configuration for the Web Application (SvelteKit)
[build]
buildCommand = "npm install -g pnpm && pnpm install && cd apps/web && pnpm run build"

[deploy]
startCommand = "cd apps/web && node build/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10