#!/usr/bin/env node

/**
 * Interactive environment setup.
 *
 * Collects a Postgres connection string (the only database MeshHook accepts;
 * the Supabase-era anon/service-role keys and the Turso-era auth token are
 * gone), the secrets encryption key and the OpenAI key, and writes the env
 * file for the chosen environment.
 */

import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import inquirer from "inquirer";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");

const ENVIRONMENTS = {
  local: {
    name: "Local development",
    file: ".env.local",
    defaultUrl: "postgres://meshhook:meshhook@localhost:5432/meshhook",
    committed: false,
  },
  staging: { name: "Staging", file: ".env.staging", defaultUrl: "", committed: false },
  production: { name: "Production", file: ".env.production", defaultUrl: "", committed: false },
};

/** Reject anything that is not a Postgres URL. */
function validateUrl(input) {
  const value = input.trim();
  if (!value) return "A database URL is required";
  if (/^(libsql|https?):\/\//i.test(value) || value.startsWith("file:")) {
    return "That is a Turso/libSQL URL. MeshHook runs on Postgres — expected postgres://";
  }
  if (!/^postgres(ql)?:\/\//i.test(value)) {
    return "Expected a postgres:// URL";
  }
  return true;
}

function buildEnv({ url, encryptionKey, openaiKey, environment }) {
  const lines = [
    `# MeshHook ${ENVIRONMENTS[environment].name} environment`,
    `# Generated by scripts/setup.js`,
    "",
    "# Database (Postgres)",
    `DATABASE_URL=${url}`,
  ];

  lines.push(
    "",
    "# Encrypts the secrets table (AES-256-GCM). Losing this makes secrets unrecoverable.",
    `SECRETS_ENCRYPTION_KEY=${encryptionKey}`,
    "",
    "# Integrations",
    `OPENAI_API_KEY=${openaiKey ?? ""}`,
    "",
    "# Application",
    `NODE_ENV=${environment === "local" ? "development" : environment}`,
    "PORT=8080",
    "",
  );

  return lines.join("\n");
}

/** Preserve an existing key so re-running setup cannot orphan stored secrets. */
function existingEncryptionKey(envPath) {
  if (!existsSync(envPath)) return null;
  const match = /^SECRETS_ENCRYPTION_KEY=(.+)$/m.exec(readFileSync(envPath, "utf8"));
  const value = match?.[1]?.trim();
  return value || null;
}

async function main() {
  console.log("🔧 MeshHook environment setup\n");

  const { environment } = await inquirer.prompt([
    {
      type: "list",
      name: "environment",
      message: "Which environment are you configuring?",
      choices: Object.entries(ENVIRONMENTS).map(([value, cfg]) => ({
        name: cfg.name,
        value,
      })),
    },
  ]);

  const config = ENVIRONMENTS[environment];
  const envPath = join(rootDir, config.file);

  if (existsSync(envPath)) {
    const { overwrite } = await inquirer.prompt([
      {
        type: "confirm",
        name: "overwrite",
        message: `${config.file} already exists. Overwrite it?`,
        default: false,
      },
    ]);
    if (!overwrite) {
      console.log("Aborted; nothing was changed.");
      return;
    }
  }

  const answers = await inquirer.prompt([
    {
      type: "input",
      name: "url",
      message: "Postgres URL (postgres://user:pass@host:5432/meshhook):",
      default: config.defaultUrl || undefined,
      validate: validateUrl,
      filter: (v) => v.trim(),
    },
    {
      type: "input",
      name: "openaiKey",
      message: "OpenAI API key (optional, press enter to skip):",
      filter: (v) => v.trim(),
    },
  ]);

  // Reuse the key if one is already present; a new key would strand every
  // secret already encrypted under the old one.
  const reused = existingEncryptionKey(envPath);
  const encryptionKey = reused ?? randomBytes(32).toString("hex");

  writeFileSync(envPath, buildEnv({ ...answers, encryptionKey, environment }), "utf8");

  console.log(`\n✅ Wrote ${config.file}`);
  if (reused) {
    console.log("   Kept the existing SECRETS_ENCRYPTION_KEY.");
  } else {
    console.log("   Generated a new SECRETS_ENCRYPTION_KEY — back it up.");
  }

  console.log("\n⚠️  This file holds credentials. Keep it out of version control.");

  console.log("\nNext steps:");
  console.log(`  1. Point .env at it:  ln -sf ${config.file} .env`);
  console.log("  2. Apply the schema:  pnpm run db:migrate");
  console.log("  3. Start the app:     pnpm run dev");
}

main().catch((error) => {
  console.error(`\n❌ Setup failed: ${error.message}`);
  process.exit(1);
});
