#!/usr/bin/env node

/**
 * Interactive environment setup.
 *
 * Rewritten for Turso. The Supabase version collected a Postgres connection
 * string plus anon and service-role keys, and told the user to run
 * `supabase start` for local work. Local development now needs nothing running
 * at all — a `file:` URL is a plain SQLite file — and production needs a
 * database URL and token from the Turso CLI.
 */

import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import inquirer from "inquirer";

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, "..");

const ENVIRONMENTS = {
  local: {
    name: "Local development",
    file: ".env.local",
    // A file URL keeps local work dependency-free; no server, no container.
    defaultUrl: "file:./meshhook.db",
    committed: false,
  },
  staging: { name: "Staging", file: ".env.staging", defaultUrl: "", committed: false },
  production: { name: "Production", file: ".env.production", defaultUrl: "", committed: false },
};

/** Reject anything that is not a libSQL-compatible URL. */
function validateUrl(input) {
  const value = input.trim();
  if (!value) return "A database URL is required";
  if (/^postgres(ql)?:\/\//i.test(value)) {
    return "That is a Postgres URL. MeshHook now uses Turso — expected libsql:// or file:";
  }
  if (!/^(libsql|file|https?):\/\//i.test(value) && !value.startsWith("file:")) {
    return "Expected a libsql://, https:// or file: URL";
  }
  return true;
}

function buildEnv({ url, token, encryptionKey, openaiKey, environment }) {
  const lines = [
    `# MeshHook ${ENVIRONMENTS[environment].name} environment`,
    `# Generated by scripts/setup.js`,
    "",
    "# Database (Turso / libSQL)",
    `TURSO_DATABASE_URL=${url}`,
  ];

  // A file: database is local and unauthenticated; a token would be meaningless.
  if (token) {
    lines.push(`TURSO_AUTH_TOKEN=${token}`);
  }

  lines.push(
    "",
    "# Encrypts the secrets table (AES-256-GCM). Losing this makes secrets unrecoverable.",
    `SECRETS_ENCRYPTION_KEY=${encryptionKey}`,
    "",
    "# Integrations",
    `OPENAI_API_KEY=${openaiKey ?? ""}`,
    "",
    "# Application",
    `NODE_ENV=${environment === "local" ? "development" : environment}`,
    "PORT=8080",
    "",
  );

  return lines.join("\n");
}

/** Preserve an existing key so re-running setup cannot orphan stored secrets. */
function existingEncryptionKey(envPath) {
  if (!existsSync(envPath)) return null;
  const match = /^SECRETS_ENCRYPTION_KEY=(.+)$/m.exec(readFileSync(envPath, "utf8"));
  const value = match?.[1]?.trim();
  return value || null;
}

async function main() {
  console.log("🔧 MeshHook environment setup\n");

  const { environment } = await inquirer.prompt([
    {
      type: "list",
      name: "environment",
      message: "Which environment are you configuring?",
      choices: Object.entries(ENVIRONMENTS).map(([value, cfg]) => ({
        name: cfg.name,
        value,
      })),
    },
  ]);

  const config = ENVIRONMENTS[environment];
  const envPath = join(rootDir, config.file);

  if (existsSync(envPath)) {
    const { overwrite } = await inquirer.prompt([
      {
        type: "confirm",
        name: "overwrite",
        message: `${config.file} already exists. Overwrite it?`,
        default: false,
      },
    ]);
    if (!overwrite) {
      console.log("Aborted; nothing was changed.");
      return;
    }
  }

  const answers = await inquirer.prompt([
    {
      type: "input",
      name: "url",
      message: "Turso database URL (or file: path for local):",
      default: config.defaultUrl || undefined,
      validate: validateUrl,
      filter: (v) => v.trim(),
    },
    {
      type: "password",
      name: "token",
      message: "Turso auth token (create with: turso db tokens create <db>):",
      mask: "*",
      // Only a remote database needs one.
      when: (a) => !a.url.startsWith("file:"),
      validate: (input) => (input.trim() ? true : "A token is required for remote databases"),
      filter: (v) => v.trim(),
    },
    {
      type: "input",
      name: "openaiKey",
      message: "OpenAI API key (optional, press enter to skip):",
      filter: (v) => v.trim(),
    },
  ]);

  // Reuse the key if one is already present; a new key would strand every
  // secret already encrypted under the old one.
  const reused = existingEncryptionKey(envPath);
  const encryptionKey = reused ?? randomBytes(32).toString("hex");

  writeFileSync(envPath, buildEnv({ ...answers, encryptionKey, environment }), "utf8");

  console.log(`\n✅ Wrote ${config.file}`);
  if (reused) {
    console.log("   Kept the existing SECRETS_ENCRYPTION_KEY.");
  } else {
    console.log("   Generated a new SECRETS_ENCRYPTION_KEY — back it up.");
  }

  console.log("\n⚠️  This file holds credentials. Keep it out of version control.");

  console.log("\nNext steps:");
  console.log(`  1. Point .env at it:  ln -sf ${config.file} .env`);
  console.log("  2. Apply the schema:  pnpm run db:migrate");
  console.log("  3. Start the app:     pnpm run dev");
}

main().catch((error) => {
  console.error(`\n❌ Setup failed: ${error.message}`);
  process.exit(1);
});
