-- Job queue, Postgres. See migrations/0003_queue.sql for the model (pgmq's
-- visibility-timeout semantics on one table with a queue_name column).
--
-- msg_id was `integer primary key` (a rowid alias) and is an identity bigint
-- here, so inserts keep returning lastInsertRowid through libsql-pg and FIFO
-- ordering by msg_id still holds.

create table if not exists queue_messages (
  msg_id bigint generated by default as identity primary key,
  queue_name text not null,
  message text not null,
  read_ct bigint not null default 0,
  enqueued_at text not null default (meshhook_now_iso()),
  -- Visibility time: invisible to readers until this instant.
  vt text not null default (meshhook_now_iso())
);

-- The dequeue hot path: oldest visible message on one queue.
create index if not exists idx_queue_messages_claim on queue_messages(queue_name, vt, msg_id);

-- Archived messages keep their original msg_id so job_tracking rows still join.
create table if not exists queue_archive (
  msg_id bigint primary key,
  queue_name text not null,
  message text not null,
  read_ct bigint not null default 0,
  enqueued_at text not null,
  archived_at text not null default (meshhook_now_iso())
);

create index if not exists idx_queue_archive_queue_name on queue_archive(queue_name);
create index if not exists idx_queue_archive_archived_at on queue_archive(archived_at desc);

create table if not exists queue_config (
  id text primary key default (gen_random_uuid()::text),
  queue_name text not null unique,
  visibility_timeout_seconds bigint not null default 30,
  max_retry_attempts bigint not null default 5,
  retry_backoff_base_ms bigint not null default 1000,
  retry_backoff_max_ms bigint not null default 300000,
  dlq_enabled bigint not null default 1 check (dlq_enabled in (0, 1)),
  created_at text not null default (meshhook_now_iso()),
  updated_at text not null default (meshhook_now_iso())
);

drop trigger if exists update_queue_config_updated_at on queue_config;
create trigger update_queue_config_updated_at
before update on queue_config for each row
execute function meshhook_set_updated_at();

insert into queue_config (
  queue_name, visibility_timeout_seconds, max_retry_attempts,
  retry_backoff_base_ms, retry_backoff_max_ms, dlq_enabled
) values ('workflow_jobs', 30, 5, 1000, 300000, 1)
on conflict (queue_name) do nothing;

-- The DLQ is terminal: zero attempts and no onward DLQ.
insert into queue_config (
  queue_name, visibility_timeout_seconds, max_retry_attempts,
  retry_backoff_base_ms, retry_backoff_max_ms, dlq_enabled
) values ('workflow_jobs_dlq', 300, 0, 0, 0, 0)
on conflict (queue_name) do nothing;

create table if not exists job_tracking (
  id text primary key default (gen_random_uuid()::text),
  msg_id bigint not null,
  run_id text not null references workflow_runs(id) on delete cascade,
  queue_name text not null,
  attempt bigint not null default 1,
  max_attempts bigint not null default 5,
  enqueued_at text not null default (meshhook_now_iso()),
  started_at text,
  completed_at text,
  failed_at text,
  moved_to_dlq_at text,
  error_message text,
  error_stack text,
  created_at text not null default (meshhook_now_iso()),
  updated_at text not null default (meshhook_now_iso())
);

create index if not exists idx_job_tracking_msg_id on job_tracking(msg_id);
create index if not exists idx_job_tracking_run_id on job_tracking(run_id);
create index if not exists idx_job_tracking_queue_name on job_tracking(queue_name);
create index if not exists idx_job_tracking_enqueued_at on job_tracking(enqueued_at desc);
create index if not exists idx_job_tracking_status on job_tracking(completed_at, failed_at, moved_to_dlq_at);

drop trigger if exists update_job_tracking_updated_at on job_tracking;
create trigger update_job_tracking_updated_at
before update on job_tracking for each row
execute function meshhook_set_updated_at();
